storage:
  dbPath: /root/mongodb_data
systemLog:
  destination: file
  path: /var/log/mongodb.log
  logAppend: true
net:
  bindIp: 127.0.0.1
  port: 27017
security:
  authorization: enabled
processManagement:
  fork: true
search:
  enabled: true
